remote_theme: "jekyll/minima@1e8a445"

sass:
  style: compressed
  load_paths:
    - _sass

title: "Hans' Blog"
author: "Hans"
email: "hans.shon@gmail.com"
description: "This is my personal blog using Jekyll and Minima."

baseurl: ""  # Keep this empty for GitHub Pages
url: "https://blog.hanspm.com"  # Change this to your custom domain

#theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
